### ISSUE TITLE
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

### ISSUE THREAD

**Issue by zaoyueri** [ChaoningZhang/MobileSAM#114]
![image](https://github.com/ChaoningZhang/MobileSAM/assets/115647574/5a2b633d-4d79-40fd-b7fc-a9f704f46861)
I am running amg. py on the local CPU and the specified checkpoint is "./weights/mobile_sam. pt". An error is reported indicating that the weight file size does not match the torchsize of the current model.

**Comment by phcbest** [comment]
I also encountered this situation, have you solved it?
