### ISSUE TITLE
How to prove that MobileSAM's performance is comparable to the original SAM?

### ISSUE THREAD

**Issue by hongyan-an** [ChaoningZhang/MobileSAM#12]
Thanks a lot for your work! When you mention that MobileSAM and SAM have comparable performance, do you mean with SAM (ViT-H)? I tried to find evidence for this idea from the paper, but only found a few visualization results. I'm really looking forward to know the quantitative comparison between MobileSAM and SAM on some tasks (such as the multiple experiments mentioned in the original SAM paper).

**Comment by ChaoningZhang** [comment]
Thanks for your kind advice. We will conduct those experiments soon. Stay tuned!

**Comment by sasdxcxzd** [comment]
> Thanks for your kind advice. We will conduct those experiments soon. Stay tuned!

Thanks a lot for your work! When you mention that MobileSAM and SAM have comparable performance, do you mean with SAM (ViT-H)? I tried to find evidence for this idea from the paper, but only found a few visualization results. I'm really looking forward to know the quantitative comparison between MobileSAM and SAM on some tasks (such as the multiple experiments mentioned in the original SAM paper).
