### ISSUE TITLE
Convert to ONNX with SAMExporter

### ISSUE THREAD

**Issue by vietanhdev** [ChaoningZhang/MobileSAM#20]
SAM Exporter has added Mobile SAM to the support models.
- Checkout: <https://github.com/vietanhdev/samexporter>.
- This implementation support exporting Encoder and Decoder separately.
- Add this repo to README if you find it useful.

**Comment by ChaoningZhang** [comment]
Thanks for your interest in our work. I let my coworker implement ONNX and he was not aware that you already did this and thus just implemented by himself. If it does not work properly, we will consider using your implementation.
