### ISSUE TITLE
how to convet the model to onnx 

### ISSUE THREAD

**Issue by qnmts** [ChaoningZhang/MobileSAM#28]
I did not convert the model to onnx according to the method provided by SAM

**Comment by jnulzl** [comment]
@qnmts 
```python
python scripts/export_onnx_model.py --checkpoint weights/mobile_sam.pt --model-type vit_t --opset 11 --output mobile_sam_onnx_opset11.onnx
```
![mobile_sam_to_onnx](https://github.com/ChaoningZhang/MobileSAM/assets/11990112/a24f1002-2ff3-4ac1-b627-4841f021876a)

**Comment by qnmts** [comment]
@jnulzl  This is my way of switching, but there are a lot of caveats,and the accuracy of ONNX's inference is not as high as before. Do you have this situation
![image](https://github.com/ChaoningZhang/MobileSAM/assets/74292184/cdd90b3e-9942-4664-bab8-a56a6b8bac5b)

**Comment by dhkim2810** [comment]
@qnmts Hi, please check this [pull request](https://github.com/ChaoningZhang/MobileSAM/pull/33).

**Comment by jnulzl** [comment]
@qnmts I didn't meet your problem

**Comment by qnmts** [comment]
> @qnmts Hi, please check this [pull request](https://github.com/ChaoningZhang/MobileSAM/pull/33).

thank you !!!

**Comment by qnmts** [comment]
> @qnmts I didn't meet your error. You can try to update your code to the latest and try again.
ok

**Comment by ChaoningZhang** [comment]
> @jnulzl This is my way of switching, but there are a lot of caveats,and the accuracy of ONNX's inference is not as high as before. Do you have this situation ![image](https://user-images.githubusercontent.com/74292184/250047111-cdd90b3e-9942-4664-bab8-a56a6b8bac5b.png)

Have you figured out the reason? If so, please kindly let us know. Thanks~~

**Comment by dhkim2810** [comment]
Hi @qnmts , we will close the issue.
Please let us know if there is performance degradation in exported ONNX model.

Thank you.
