### ISSUE TITLE
Unable to replicate SAM results

### ISSUE THREAD

**Issue by alexcbb** [ChaoningZhang/MobileSAM#34]
Hello,

Thank you for you work. I've tried to replace your model instead of using SAM in a visualisation pipeline that i've setup. The problem is that I'm unable to obtain as good results as with original SAM, even compared to the Vit-b version. On my test with AutoMask, your model is unable to separate objects as SAM can do. Is the model given in weights your trained model and if yes do you have any clue on what could be wrong ? (the preprocessing is OK as my code is working with original SAM)

Thank you in advance !

**Comment by ChaoningZhang** [comment]
> Hello,
> 
> Thank you for you work. I've tried to replace your model instead of using SAM in a visualisation pipeline that i've setup. The problem is that I'm unable to obtain as good results as with original SAM, even compared to the Vit-b version. On my test with AutoMask, your model is unable to separate objects as SAM can do. Is the model given in weights your trained model and if yes do you have any clue on what could be wrong ? (the preprocessing is OK as my code is working with original SAM)
> 
> Thank you in advance !

Thanks for your interest in our work. After our model with pretrained weights is publicly available, it’s the first time that we receive such an issue like this. We provide a demo on hugging face, can you at least get a reasonable results in this simple setup?

**Comment by alexcbb** [comment]
The demo is not working at all, each time I want to try to segment an image I get an error as return : 
![Screenshot from 2023-06-30 16-44-04](https://github.com/ChaoningZhang/MobileSAM/assets/16562497/5356c5c8-46d2-4101-8807-b7ecac9e6ef5)

**Comment by ChaoningZhang** [comment]
> The demo is not working at all, each time I want to try to segment an image I get an error as return :
> ![Screenshot from 2023-06-30 16-44-04](https://user-images.githubusercontent.com/16562497/250119653-5356c5c8-46d2-4101-8807-b7ecac9e6ef5.png)

I just tested it and the demo indeed Suddenly crashed with a error. It worked normally before, I kinda know what might be wrong, but need to let my coworkers give it a check tomorrow. Now it’s 4:13am in Korea, thanks for your understanding and letting us know that the demo suddenly doesn’t work.

**Comment by ChaoningZhang** [comment]
> The demo is not working at all, each time I want to try to segment an image I get an error as return : ![Screenshot from 2023-06-30 16-44-04](https://user-images.githubusercontent.com/16562497/250119653-5356c5c8-46d2-4101-8807-b7ecac9e6ef5.png)

Thanks for notifying us of this issue which has been solved. Please check the demo again.

**Comment by ChaoningZhang** [comment]
> The demo is not working at all, each time I want to try to segment an image I get an error as return :
> ![Screenshot from 2023-06-30 16-44-04](https://user-images.githubusercontent.com/16562497/250119653-5356c5c8-46d2-4101-8807-b7ecac9e6ef5.png)

Another demo showing MobileSAM working in your local browser is available at https://mobilesam.glitch.me/ Please also give it a check. Hope it is helpful for you.
