### ISSUE TITLE
Faster Segment Anything (MobileSAM) taking 20 seconds and erroring out

### ISSUE THREAD

**Issue by patricibal** [ChaoningZhang/MobileSAM#36]
Hi,

I am experiencing an issue with Faster Segment Anything (MobileSAM) where it is taking 20 seconds to run sometimes, and errors out each time. I have also tried placing over 10 points on an image, but it is still taking a long time and not working.

Here are the steps I am taking to reproduce the issue:

I open https://huggingface.co/spaces/dhkim2810/MobileSAM 
I open the image in MobileSAM, using my own and example images provided. 
I Select a point with Add Mask 
I place points on the image 
I click the "Start segmenting" button
The issue occurs when the "Start segmenting" button is clicked. The process sometimes takes 8, 10, and 20 seconds, and each time it errors out with the following message: Error.

I have tried the following to try to fix the issue:

I have tried using different images, but the issue still occurs.
I am running MobileSAM on a HP Spectre x360

I would appreciate it if you could look into this issue and let me know if there is anything I can do to fix it.

Thanks,
Patrici Bal

**Comment by ChaoningZhang** [comment]
> Hi,
> 
> I am experiencing an issue with Faster Segment Anything (MobileSAM) where it is taking 20 seconds to run sometimes, and errors out each time. I have also tried placing over 10 points on an image, but it is still taking a long time and not working.
> 
> Here are the steps I am taking to reproduce the issue:
> 
> I open https://huggingface.co/spaces/dhkim2810/MobileSAM I open the image in MobileSAM, using my own and example images provided. I Select a point with Add Mask I place points on the image I click the "Start segmenting" button The issue occurs when the "Start segmenting" button is clicked. The process sometimes takes 8, 10, and 20 seconds, and each time it errors out with the following message: Error.
> 
> I have tried the following to try to fix the issue:
> 
> I have tried using different images, but the issue still occurs. I am running MobileSAM on a HP Spectre x360
> 
> I would appreciate it if you could look into this issue and let me know if there is anything I can do to fix it.
> 
> Thanks, Patrici Bal

I just tested it and the demo indeed Suddenly crashed with a error. It worked normally before, I kinda know what might be wrong, but need to let my coworkers give it a check tomorrow. Thanks for your patience and letting us know that the demo suddenly doesn’t work.

**Comment by ChaoningZhang** [comment]
> let

Thanks for notifying us of this issue again. The problem seems to be solved (please check the demo) and I will close this issue. If you encounter new issues, please kindly let us know. Thanks~~

**Comment by ChaoningZhang** [comment]
> Hi,
> 
> I am experiencing an issue with Faster Segment Anything (MobileSAM) where it is taking 20 seconds to run sometimes, and errors out each time. I have also tried placing over 10 points on an image, but it is still taking a long time and not working.
> 
> Here are the steps I am taking to reproduce the issue:
> 
> I open https://huggingface.co/spaces/dhkim2810/MobileSAM I open the image in MobileSAM, using my own and example images provided. I Select a point with Add Mask I place points on the image I click the "Start segmenting" button The issue occurs when the "Start segmenting" button is clicked. The process sometimes takes 8, 10, and 20 seconds, and each time it errors out with the following message: Error.
> 
> I have tried the following to try to fix the issue:
> 
> I have tried using different images, but the issue still occurs. I am running MobileSAM on a HP Spectre x360
> 
> I would appreciate it if you could look into this issue and let me know if there is anything I can do to fix it.
> 
> Thanks, Patrici Bal

Thanks for notifying us of this issue which has been solved. I close this issue. Please check the demo again. Please kindly let us know in case you encounter new issues.

**Comment by patricibal** [comment]
Hi!

It is working great!

Thank you
