### ISSUE TITLE
More training data?

### ISSUE THREAD

**Issue by Aodamiaomiao** [ChaoningZhang/MobileSAM#5]
Great work! I wonder that if we use more training data (~10% or more) to train the mobile-sam, will we get a more powerful model?

**Comment by ChaoningZhang** [comment]
> Great work! I wonder that if we use more training data (~10% or more) to train the mobile-sam, will we get a more powerful model?

Good question, we started with 0.1% data which performs slightly worse than 1%, but the gap seems to be not very large. With 10% or more, it is expected that the performance will further increase. What we found is that training for more epochs will increase more. We completed training on a single GPU within less than one day. We stoped training, after we observed that the performance is already very good, sufficiently close to the original SAM. However, more training can definitely improve.

**Comment by Aodamiaomiao** [comment]
Thanks, looking forward for release of the training/finetuing code
