### ISSUE TITLE
import onnx error

### ISSUE THREAD

**Issue by d710055071** [ChaoningZhang/MobileSAM#55]
asttokens              2.2.1
backcall               0.2.0
certifi                2022.12.7
charset-normalizer     3.1.0
coloredlogs            15.0.1
comm                   0.1.3
contourpy              1.0.7
cycler                 0.11.0
debugpy                1.6.7
decorator              5.1.1
executing              1.2.0
filelock               3.12.2
flatbuffers            23.5.26
fonttools              4.39.2
fsspec                 2023.6.0
huggingface-hub        0.15.1
humanfriendly          10.0
idna                   3.4
imgviz                 1.2.6
importlib-metadata     6.7.0
importlib-resources    5.12.0
ipykernel              6.24.0
ipython                8.12.2
jedi                   0.18.2
jupyter_client         8.3.0
jupyter_core           5.3.1
kiwisolver             1.4.4
mahotas                1.4.13
matplotlib             3.7.1
matplotlib-inline      0.1.6
mobile-sam             1.0          /mnt/sda/code/MobileSAM-master
mpmath                 1.3.0
nest-asyncio           1.5.6
numpy                  1.24.2
onnx                   1.12.0
onnxruntime-gpu        1.13.1
opencv-python          4.7.0.72
opencv-python-headless 4.5.3.56
packaging              23.0
parso                  0.8.3
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 9.4.0
pip                    23.0.1
platformdirs           3.8.0
prompt-toolkit         3.0.38
protobuf               3.20.1
psutil                 5.9.5
ptyprocess             0.7.0
pure-eval              0.2.2
Pygments               2.15.1
pyparsing              3.0.9
PyQt5                  5.15.7
PyQt5-Qt5              5.15.2
PyQt5-sip              12.12.1
python-dateutil        2.8.2
PyYAML                 6.0
pyzmq                  25.1.0
requests               2.31.0
safetensors            0.3.1
segment-anything       1.0          /mnt/sda/code/segment-anything-main
setuptools             65.6.3
six                    1.16.0
stack-data             0.6.2
sympy                  1.12
timm                   0.9.2
torch                  1.10.1+cu111
torchaudio             0.10.1+cu111
torchvision            0.11.2+cu111
tornado                6.3.2
tqdm                   4.65.0
traitlets              5.9.0
typing_extensions      4.5.0
urllib3                2.0.3
wcwidth                0.2.6
wheel                  0.38.4
zipp                   3.15.0

(cam) dongzf@dongzf-LEGION-REN7000P-26AMR:/mnt/sda/code/MobileSAM-master$ python scripts/export_onnx_model.py --checkpoint ./weights/mobile_sam.pt --model-type vit_t --output ./mobile_sam.onnx
Loading model...
Exporting onnx model to ./mobile_sam.onnx...
Traceback (most recent call last):
  File "scripts/export_onnx_model.py", line 176, in <module>
    run_export(
  File "scripts/export_onnx_model.py", line 148, in run_export
    torch.onnx.export(
  File "/home/dongzf/miniconda3/envs/cam/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/dongzf/miniconda3/envs/cam/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/dongzf/miniconda3/envs/cam/lib/python3.8/site-packages/torch/onnx/utils.py", line 707, in _export
    _set_opset_version(opset_version)
  File "/home/dongzf/miniconda3/envs/cam/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 849, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 16

**Comment by dhkim2810** [comment]
Hi @d710055071 , this is due to torch ONNX compatibility.
You can update to latest PyTorch or use slightly lower poset version such as 11.
We recommend using latest `PyTorch>2.0`.

**Comment by d710055071** [comment]
torch-1.12.0 is ok

**Comment by dhkim2810** [comment]
@d710055071,

We will close the issue.
Thanks for your interest in our project.
