### ISSUE TITLE
how to import encoded model onnx?

### ISSUE THREAD

**Issue by d710055071** [ChaoningZhang/MobileSAM#56]

**Comment by dhkim2810** [comment]
Please take a look at this notebook.
[ONNX Guide](https://github.com/ChaoningZhang/MobileSAM/blob/master/notebooks/onnx_model_example.ipynb)

Thank you.

**Comment by d710055071** [comment]
Only the decoded onnx here, not the image encoded onnx

**Comment by ryouchinsa** [comment]
You can find the converter for the encoding part to the onnx format in the repository [Segment Anything CPP Wrapper](https://github.com/dinglufe/segment-anything-cpp-wrapper).
