### ISSUE TITLE
Question about the segment_anything part in this code

### ISSUE THREAD

**Issue by mrbulb** [ChaoningZhang/MobileSAM#9]
Hello, thank you for your great work!
I notice the the `segment_anything` part in the code has the same code structure compared with the original [SAM](https://github.com/facebookresearch/segment-anything/tree/main/segment_anything).
Is there any modification for this part?
And if I want to integrate MobileSAM into the project with SAM, all I need to do is to add the [mobile_encoder](https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_encoder) to the original project ?

**Comment by qiaoyu1002** [comment]
Hello，thank your for your interest in our work.

We did not modify the segment_anything part in the original code, therefore it is easy for readers to follow!
We provide the example for usage in the notebooks, please kindly check that. Also, If you want to integrate MobileSAM into other projects, currently the mobile_encoder and weights folder is necessary.  If you have more questions, please let us know.
